# Generated by Django 2.0.6 on 2020-08-30 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('salary', models.IntegerField()),
                ('age', models.IntegerField()),
                ('head_pic', models.ImageField(upload_to='pic')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('user_pwd', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=10)),
            ],
        ),
    ]
